FROM nginx:alpine

# Copiar el HTML, CSS y JS al directorio raíz de NGINX
COPY index.html /usr/share/nginx/html/index.html
COPY styles.css /usr/share/nginx/html/styles.css
COPY script.js /usr/share/nginx/html/script.js